### ISSUE TITLE
Priklad 7/Lekce 2

### ISSUE THREAD

**Issue by mfa1980** [mfa1980/python-012021#14]
@lutydlitatova
Ahoj Lido, zasilam chybejici priklad c. 7, prosim o kontrolu. Je ve folder Lekce 2, diky, Mirka

**Comment by lutydlitatova** [comment]
Skvěle! S touhle úlohou myslím hodně účastnic kurzu bojovalo. Jak to šlo?

**Comment by mfa1980** [comment]
Prozatím asi nejtěžší úkol:). Slovníky mi obecně mi moc nesedí, seznamy a dataframe jsou pro mě víc uchopitelné... hodně jsem se s tím natrápila, pokus omyl:)
