### ISSUE TITLE
Priklad 9/Lekce 2

### ISSUE THREAD

**Issue by mfa1980** [mfa1980/python-012021#15]
@lutydlitatova
Ahoj Lido, zasilam chybejici priklad c. 9, prosim o kontrolu. Je ve folderu Lekce 2, diky, Mirka

**Comment by lutydlitatova** [comment]
Skoro správně - zkus program upravit tak, aby podle stejných pravidel známkování fungoval i pro takovýhle slovník známek. Liší se od toho původního tak, že Mirek Dušín má trojku z angličtiny (místo dvojky v zadání), takže by "prospěl", ale v současnosti by tvůj program napsal, že prospěl s vyznamenáním a Jarka Metelka má stejné známky, akorát prohozený zápis (Ekonomika s Dějepisem), takže stejně jako původně by měl "neprospět", ale program by teď napsal, že prospěl.

```python
vysledky = [
  {"Jméno": "Mirek Dušín", "Český jazyk": 1, "Anglický jazyk": 3, "Matematika": 1, "Biologie": 1, "Zeměpis": 1},
  {"Jméno": "Jarka Metelka", "Český jazyk": 3, "Anglický jazyk": 1, "Matematika": 3, "Ekonomika": 5, "Dějepis": 2}
]
```

Kdyžtak hned napiš, kdyby nebylo jasné, jak to opravit a poradím, jak na to 🙂

**Comment by mfa1980** [comment]
Dekuji...ozvu se :-)

**Comment by mfa1980** [comment]
@lutydlitatova
Ahoj, až budeš mít čas, prosím mrkni na to :-). Příklad 9, upravený najdeš v lekce č. 2, děkuji.

**Comment by lutydlitatova** [comment]
👍  Super, to vypadá pěkně! Takže píšu 5 bodů za sadu úkolů 2.

Jediná poznámka (není potřeba upravovat, jen pro tebe):
Na řádce [51](https://github.com/mfa1980/python-012021/blob/cb076c5f75dec36a15da5fd376cac8bc23bc7b50/Lekce%202/Ukoly/priklad09%20-%20upraveno.py#L51) se výraz `(3 or 4)` vždy vyhodnotí jako  `3`. Zkus si to například takhle v programu:

```python
print(3 or 4)  # vypise `3`

if (3 or 4) in [4, 8, 12]:
    print("3 or 4 in [4, 8, 12]")  # nevypise se!
```

Pokud bychom chtěli zjistit, jestli se ve známkách nachází trojka nebo čtyřka, museli bychom to rozdělit na dvě části podmínky:

```python
if 3 in zaznam.values() or 4 in zaznam.values():
    print(f"{jmeno}: Prospěl")
```

**Comment by mfa1980** [comment]
Ahoj, díky za opravu a jj, chápu, děkuji :-).
