### ISSUE TITLE
Fakova Mirka_hotove priklad 6,8,10

### ISSUE THREAD

**Issue by mfa1980** [mfa1980/python-012021#2]
@lutydlitatova
Ahoj Lido,posilam hotove domaci ukoly 6,8,10. Najdes se ve folder 2 lekce, domaci ukoly...omlouvam se, zatim vic prikladu nemam. Mam v praci peklo, nestiham, jak mam pres den deti doma. A omylem se mi na Git nahralo vse, co mam v Pycharm, proto tolik souboru a zmatku  : -((...jak to prosim mohu vymazat z Gitu?..dekuji moc, Mirka

**Comment by lutydlitatova** [comment]
Ahoj Mirko, úkoly jsou super! Pěkná a čistá řešení, díky!
Vím že je to teď pro spoustu účastnic kurzu docela napjaté a náročné období, takže v tom nejsi sama a my to rozhodně zohledníme - není za co se omlouvat, pro mne jsou pracující rodiče s dětmi doma absolutní hrdinové a hrdinky dnešní doby 🙂

**Comment by lutydlitatova** [comment]
>A omylem se mi na Git nahralo vse, co mam v Pycharm, proto tolik souboru a zmatku : -((...jak to prosim mohu vymazat z Gitu?

Co se týče gitu, obecně to nevadí, ale dá se to samozřejmě spravit! Nejlépe asi pomocí příkazu `git rm --cached <nazev-souboru>`, který se spustí z terminálu. Nevím, jestli máš chvilku se dneska zastavit na konzultacích, kdyby náhodou ano, tak se na to můžeme podívat spolu. Jinak popíšu podrobnější návod sem 🙂

**Comment by mfa1980** [comment]
Ahoj Lido, diky moc, jsi super povzbuzujici! Snad se to casove zlepsi a zase dalsi cast poslu...
Rada bych na konzultace, ale ty pondelky nemuzu a divam se obcas ze zaznamu. A asi se na popis vymazu tech vsech souboru z Gitu vyprdni, at tim neztracis cas...a kdyztak to doladime pozdeji. Verim, ze az zase zacnou fungovat skolky, bude lip : -) ))).
Mej se zatim krasne a moc diky za vas support, M.

**Comment by mfa1980** [comment]
Vše vyřešeno, ukončuji issue.
