### ISSUE TITLE
Priklady36-40, Pujcovna

### ISSUE THREAD

**Issue by mfa1980** [mfa1980/python-012021#22]
@lutydlitatova
Ahoj Lido, nahrala jsem pod Lekci 8 podklady k prikladum 36-40. Prosim o kontrolu, az budes mit cas, dekuji.

**Comment by mfa1980** [comment]
GitGuardian   has detected the following Django Secret Key exposed within your GitHub   account.
--
Details   -   Secret type: Django   Secret Key   -   Repository: mfa1980/python-012021   -   Pushed date: April 12th 2021, 20:52:34 UTC
Protect your   GitHub repos

**Comment by mfa1980** [comment]
Lido, mam dotaz...prisla mi hlaska vyse do emailu po nahrati souvúboru. Je to v pohode, to je standardni? Dekuji, M.

**Comment by mfa1980** [comment]
Details   -   Secret type: Django   Secret Key   -   Repository: mfa1980/python-012021   -   Pushed date: April 12th 2021, 20:52:34 UTC
--
Protect your   GitHub repos

**Comment by mfa1980** [comment]
zbytek hlasky :-)

**Comment by lutydlitatova** [comment]
Vypadá to dobře, nezkoušela jsem stáhnout a spustit, ale moje řešení mám stejně. Takže jestli nemáš otázky, a stránka ti běží, tak píšu 5 bodů za osmou sadu. 

Hlášku o Django Secret Key jsme probrali v lekci, ve zkratce - je to OK, protože stránka běží jen lokálně u tebe 🙂

**Comment by mfa1980** [comment]
Super, diky moc. Ano, stranka mi bezu a za vysvetleni Django Secret Key dekuji! Mej se krasne :-), M.
