### ISSUE TITLE
Ukol z 9 a10 lekce

### ISSUE THREAD

**Issue by mfa1980** [mfa1980/python-012021#23]
@lutydlitatova
Ahoj Lído, na Git jsem nahrála úkoly z 9 a 10 lekce. Je to v jednom, protože to navazuje. Mám k tomu prosím 2 dotazy:

Úkol 48 dobrovolný doplněk - je možné udělat výpočet tak, aby se ukazoval pouze počet dnů, nikoliv i čas 00:00:00?
Otázky obecně ke stylu stránky katalog - jak tam dostat CSS styl ze šablony base? Musela bych ve View upravit IndexView z "List" na "ListView"? Anebo je možné nějak zadat například typ barva písma v rámci funkce get? 

Díky moc, měj se krásně, Mirka

**Comment by lutydlitatova** [comment]
Ahoj, vypadá to skvěle!

> Úkol 48 dobrovolný doplněk - je možné udělat výpočet tak, aby se ukazoval pouze počet dnů, nikoliv i čas 00:00:00?

Ano, jde to, například takhle, všimni si taky, že `now` nemusí být atribut třídy (nemusí mít `self.`, protože jinde než v téhle funkci tu hodnotu nepotřebujeme):

```python
  @property
  def technicka(self):
    now = datetime.date.today()
    cas_od_TK = now - self.datum_TK
    return cas_od_TK.days  # pripadne by slo take treba: `return f"{cas_od_TK.days} dnů"`
```

> Otázky obecně ke stylu stránky katalog - jak tam dostat CSS styl ze šablony base? Musela bych ve View upravit IndexView z "List" na "ListView"? Anebo je možné nějak zadat například typ barva písma v rámci funkce get?

Mohli bychom využít `TemplateView` (viz [dokumentace](https://docs.djangoproject.com/en/3.2/ref/class-based-views/base/#templateview)). Takhle by pak mohl vypadat tvůj `IndexView`, načetl by obsah `base.html`:

```python
class IndexView(TemplateView):
    template_name = "katalog/base.html"
```

Povedla se ti vyzkoušet i úloha 50? Máš ještě nějaké otázky?

**Comment by mfa1980** [comment]
@lutydlitatova
Ahoj Lído, nahrála jsem na Git upravené soubory.  
První dotaz - díky, funguje :-).
Druhý dotaz - nastavila jsem, ale stále to styl nenačítá.
Úkol 50 - je to tam nastavené, funguje mezi stránkami na stejné úrovni, ale nenačítá se mi úvodní stránka katalog - tj. nefunguje odkaz "zpět na úvodní stránku"  (objevují se tam zákazníci)
{% url "katalog" as url_katalog %}
<p><a href="{{url_katalog}}">Zpět na úvodní stránku</a></p>
Píše se to prosím nějak speciálně? Díky!

**Comment by lutydlitatova** [comment]
Ahoj,

k té `base.html`: Krom změny na `TemplateView` musíme také přesunou obsah `get()` do těla šablony (a zbavit se celé `get()`, kterou už nepotřebujeme):

```html
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        body {
            color: black;
            font-family: Arial, Helvetica, sans-serif;
            font-size: 20px;
            line-height: 1.5;
        }
        h1,h2 {
            color: green;
            font-family: Arial, Helvetica, sans-serif;
        }
        tr, td {
            padding: 10px;
            border-spacing:3;
        }
    </style>
</head>
<body>
<!--Zde je to, co bylo v IndexView.get():-->
<h1>Vítejte v naší autopůjčovně!</h1>
<h2>Důležité odkazy</h2>
...
</body>
</html>
```

A pak url:
Zkus se zbavit řádků [23, 24 a 25 v `pujcovna/urls.py`](https://github.com/mfa1980/python-012021/blob/7e565589ff1e7dfda1c3b16a63037a580aa3b170/Lekce%209_10/Ukoly_pujcovna_9_10_upravene/pujcovna/urls.py#L23), které tam jsou navíc. Stačí odkázat na aplikaci `katalog`, která už pak má svoje `urls.py`, které jsou relativní vůči cestě `katalog/`. Tohle jsem myslím jednou chybně ukázala během lekce nebo konzultace, takže se omlouvám 🙂 . Teď jsem si to zkusila a odkazy mi v tvém projektu běhaly správně. 

Body už napíšu, ale ještě se klidně doptej! Pěkná práce!

**Comment by mfa1980** [comment]
@lutydlitatova
Ahoj Lido, moc se omlouvam za odmlku, ale nestihala jsem v praci. Moc diky za kontrolu, info a vysvetleni. Ted uz mi je vse jasne :-), mam upraveno, dekuji! M.

**Comment by lutydlitatova** [comment]
Skvěle 👍
