### ISSUE TITLE
Ukoly 11 lekce

### ISSUE THREAD

**Issue by mfa1980** [mfa1980/python-012021#24]
@lutydlitatova
Ahoj Lido, nahrala jsem na Git posledni ukoly, a prosim o jejich kontrolu.
Je tam vse krome "doplňku u prikladu 53"...to je dalsi uceni a na to ted bohuzel nemam cas : -/. Ale mohla bych te poprosit o reseni, abych si to dle toho pak zkontrolovala, az se k tomu dostanu?
Dekuji, krasny den, M.

**Comment by lutydlitatova** [comment]
Ahoj, skvěle! 🙂 Píšu 5 bodů.

@andywaltlova nahrává řešení příkladů sem: https://github.com/andywaltlova/python-012021 , takže se na to koukni, a kdyby něco chybělo, tak můžeš napsat mně nebo přímo Andy, případně rovnou udělat pull request s vylepšením 😉

**Comment by mfa1980** [comment]
@lutydlitatova
Ahoj Lido, diky moc za vse a mej se krasne!

**Comment by lutydlitatova** [comment]
@mfa1980 
Ahoj, taky, ať se ti daří!! ✨
