### ISSUE TITLE
Fakova_priklady 11 az 20

### ISSUE THREAD

**Issue by mfa1980** [mfa1980/python-012021#3]
Ahoj Lido, @lutydlitatova
na Github jsem vlozila hotove priklady11 az 20. Prosim o kontrolu, az na to budes mit cas. 
Jinak ten neporadek spatnych files jsem snad dobre smazala :-).
Dekuji, krasny den, Mirka

**Comment by lutydlitatova** [comment]
#### 11
Skvěle 👍 

#### 12
Je to na dobré cestě - doplň ještě do funkce `pujc_auto` změnu atributu `self.volne` na `False`, pokud je auto volné. Nemusíš to pak dělat manuálně jako na řádkách 36 a 40. Bude to vypadat asi takhle:
```python
class Auto:
    def __init__(self, registracni_znacka, znacka_typ, kilometry, volne=True):
        ...

    def pujc_auto(self):
        if self.volne:
            # nastav self.volne na False
            return f"Potvrzuji zapůjčení vozidla."
        else:
            return f"Vozidlo není k dispozici."
```

#### 13
Super 👍  Jediný tip je zbavit se řádky 31 `cena = 0`, tu nepotřebujeme.

#### 14
Pěkně 👍  Klidně se zbav řádky `net_salary = 0`. `self.salary` a `self.children` nemusíme převádět na `int`, protože už je zadáváme jako čísla.

#### 15
Super řešení 👍 

Za třetí sadu píšu zatím 4 body 🙂

**Comment by mfa1980** [comment]
Ahoj Lído,@lutydlitatova
Příklad 19a - pro info, to že from forex_python.converter import CurrencyRates  se píše pouze jednou vím, bylo vypracováno, aby každá část fungovala samostatně.
-Převodník - jak je prosím myšleno, že psát pouze jednou, když se pokaždé převádí na jinou měnu? A nebo je možné vše napsat nějak do jednoho? Tomu moc nerozumím, jak to myslíš :-).
Příklad 19b - ty nuly smažu. Ale dotaz k tomu - je to s nimi vyloženě špatně, protože i takto mi to funguje, anebo jsou tam jenom "navíc" a tedy je lepší je tam nepsat?
Čtvrtá sada - je tam 5 příkladů, píšeš 4 body - prosím mám něco opravit z této sady?
Díky, M.

**Comment by lutydlitatova** [comment]
Ahoj, 

K převodníku - stačí jednou vytvořit objekt `prevodnik`, a pak ho můžeme použít na víc měn, například takhle:
```python
from forex_python.converter import CurrencyRates
prevodnik = CurrencyRates()
print(f"100 USD = {prevodnik.convert('USD', 'CZK', 100)} CZK")
print(f"100 EUR = {prevodnik.convert('EUR', 'CZK', 100)} CZK")
print(f"100 DKK = {prevodnik.convert('DKK', 'CZK', 100)} CZK")
```
Ale teď už chápu, jak jsi to myslela s tím opakováním importu i převodníku, aby každá část příkladu fungovala zvlášť, takže máš plný počet bodů za čtvrtou sadu 🙂

**Comment by lutydlitatova** [comment]
Řádky navíc v principu nevadí běhu programu, je to spíš věc dobrého zvyku nebo nepsané dohody mít v programu jen příkazy, které skutečně něco dělají (pokud to nejsou například komentáře, zakomentované varianty kódu, rozpracovaná práce atd.).
V Pythonu obecně proměnné používáme až ve chvíli, kdy máme čím je naplnit, ale existují i jiné jazyky, jako třeba C++, ve kterých je zvykem proměnné napřed "deklarovat" ještě předtím, než jsou použity v nějakém příkazu. Trochu mi to připomnělo ten tvůj zápis, ale program funguje samozřejmě stejně 🙂

**Comment by mfa1980** [comment]
Ahoj Lído @lutydlitatova, děkuji moc za vysvětlení a kontrolu. Konečně jsem si provedla pořádek na Githubu a nahrála zde opravený příklad č. 12. Dále jsem nově přidala hotové příklady č. 21 až 30. Vše najdeš ve folders dle lekcí. 
Předem děkuji za kontrolu, Mirka 
PS: Pro info, chybí mi k dodání úkol č. 7 a 9 a bonus u 30tky :-). Můžes mi prosím potvrdit, že to tak je? Díky moc!

**Comment by lutydlitatova** [comment]
#### 12
Super 👍

Jinak je to myslím přesně jak píšeš, krom 7 a 9 máš vše 🙂 Hned se podívám na ty nově přidané úkoly. Vytvoříš jim prosím zvlášť Issue?

**Comment by mfa1980** [comment]
Díky moc. Ok, jasně, toto Issue uzavřu a založím na každý příklad zvlášť Issue. Dobrou
